services:
  postgres:
    image: postgres:18.4-bookworm # versão do postgres atualmente
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  pgadmin-compose:
    image: dpage/pgadmin4:2026-06-18-3 # versão do pgadmin atualmente
    environment:
      PGADMIN_DEFAULT_EMAIL: "lucivaldojr25@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "luci1987"
    ports:
      - "54321:80"
    depends_on:
      - postgres